const axios = require("axios")

async function generateImage(prompt) {

    const servers = [

        // Server 1 — Pollinations (fastest)
        async () => {

            const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=1024&seed=${Date.now()}`

            const res = await axios.get(url, {
                responseType: "arraybuffer",
                timeout: 30000
            })

            return Buffer.from(res.data)
        },

        // Server 2 — Pollinations HD
        async () => {

            const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt + ", ultra detailed, 4k")}?width=1280&height=1280`

            const res = await axios.get(url, {
                responseType: "arraybuffer",
                timeout: 30000
            })

            return Buffer.from(res.data)
        },

        // Server 3 — Dummy fallback (never fails)
        async () => {

            const url = `https://dummyimage.com/1024x1024/000/fff.png&text=${encodeURIComponent(prompt)}`

            const res = await axios.get(url, {
                responseType: "arraybuffer",
                timeout: 15000
            })

            return Buffer.from(res.data)
        }

    ]

    for (const server of servers) {
        try {

            const img = await server()

            if (img && img.length > 0) {
                return img
            }

        } catch (err) {

            console.log("Image server failed:", err.message)

        }
    }

    throw new Error("All image servers failed")
}

module.exports = {
    name: "image",

    async execute(sock, msg, args, user, data, dbPath, analytics) {

        try {

            const chatId = msg.key.remoteJid
            const prompt = args.trim()

            if (!prompt) {
                return "🖼 Usage: *.image cyber cobra warrior*"
            }

            await sock.sendMessage(chatId,{
                text:`🎨 Creating image for: *${prompt}*`
            },{quoted:msg})

            const buffer = await generateImage(prompt)

            await sock.sendMessage(chatId,{
                image: buffer,
                caption:`🖼 *${prompt}*\n\nGenerated by Cobra`
            },{quoted:msg})

            return null

        } catch(err){

            console.log("IMAGE ERROR:",err)

            return "⚠ Failed to generate image"

        }
    }
}